name: toml_localizations
description: A minimal TOML localization package built on LocalizationsDelegate.
version: 0.4.0
homepage: https://github.com/erf/toml_localizations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  toml: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

