name: toml_localizations
description: TOML localization built on LocalizationsDelegate.
version: 0.2.2
homepage: https://github.com/erf/toml_localizations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  toml: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

