name: toml_localizations
description: A minimal TOML localization package built on LocalizationsDelegate.
version: 2.7.0+1
homepage: https://github.com/erf/toml_localizations

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  toml: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1
