str = "Den hurtige brune ræv springer over den doven hund."

literal_str = 'C:\Users\nodejs\templates'

multiline_str = """\
Den hurtige brune \
ræv hopper over \
den doble hund. \
"""

literal_multiline_str = '''
Den første nye linje er
trimmet i rå strenge.
    Al anden hvidafstand
    er bevaret.
'''
