str = "Den kvikkbrune reven hopper over den late hunden."

literal_str = 'C:\Users\nodejs\templates'

multiline_str = """\
Den kjappe brune \
reven hopper over \
den late hunden. \
"""

literal_multiline_str = '''
Den første nye linjen er
trimmet i rå strenger.
    Alt annet mellomrom
    er bevart.
'''